import React from "react"
import type { MDXComponents } from "mdx/types"
import { slugify } from "@/lib/utils"
import { CollapsibleCode } from "@/components/collapsible-code"

function headingId(children: React.ReactNode): string {
  const text =
    typeof children === "string"
      ? children
      : Array.isArray(children)
        ? children.map((c) => (typeof c === "string" ? c : "")).join("")
        : ""
  return slugify(text)
}

export function useMDXComponents(components: MDXComponents): MDXComponents {
  return {
    h1: ({ children }) => (
      <h1
        id={headingId(children)}
        className="scroll-mt-[140px] text-[28px] font-bold text-[#3f3d39] leading-[1.35] mt-12 mb-5"
      >
        {children}
      </h1>
    ),

    h2: ({ children }) => (
      <h2
        id={headingId(children)}
        className="scroll-mt-[140px] text-[21px] font-bold text-[#3f3d39] leading-[1.4] mt-10 mb-4 pb-2.5 border-b border-[#e2d8c8]"
      >
        {children}
      </h2>
    ),

    h3: ({ children }) => (
      <h3
        id={headingId(children)}
        className="scroll-mt-[140px] text-[17px] font-semibold text-[#52525c] leading-[1.5] mt-7 mb-3"
      >
        {children}
      </h3>
    ),

    p: ({ children }) => (
      <p
        className="text-[16px] text-[#52525c] leading-[1.8] mb-5"
      >
        {children}
      </p>
    ),

    ul: ({ children }) => (
      <ul
        className="mdx-ul mb-5 space-y-1.5 pl-0"
      >
        {children}
      </ul>
    ),

    ol: ({ children }) => (
      <ol
        className="mdx-ol mb-5 space-y-1.5 pl-0 list-none"
        style={{ counterReset: "mdx-ol" }}
      >
        {children}
      </ol>
    ),

    li: ({ children }) => (
      <li
        className="mdx-li relative text-[16px] text-[#52525c] leading-[1.75] pl-6"
      >
        {children}
      </li>
    ),

    blockquote: ({ children }) => (
      <blockquote className="relative my-6 rounded-r-[10px] border-l-[3px] border-[#d8b892] bg-[#f0ebe3] pl-5 pr-5 py-4">
        <div className="text-[15.5px] italic text-[#6b665e] leading-[1.75]">
          {children}
        </div>
      </blockquote>
    ),

    pre: ({ children, ...props }) => {
      // Count the [data-line] spans inside the <code> child to decide whether to collapse.
      // Structure: pre → code → span[data-line] (generated by rehype-pretty-code).
      const codeEl = React.Children.toArray(children).find(
        (c): c is React.ReactElement<{ children?: React.ReactNode }> =>
          React.isValidElement(c),
      )
      const lineCount = codeEl
        ? React.Children.toArray(codeEl.props?.children).filter((c) => {
            if (!React.isValidElement(c)) return false
            const p = (c as React.ReactElement<Record<string, unknown>>).props
            return "data-line" in p
          }).length
        : 0

      return (
        <CollapsibleCode
          lineCount={lineCount}
          {...(props as React.HTMLAttributes<HTMLPreElement>)}
        >
          {children}
        </CollapsibleCode>
      )
    },

    hr: () => <hr className="my-10 border-[#e2d8c8]" />,

    a: ({ href, children }) => (
      <a
        href={href}
        className="text-[#8b6b4a] underline underline-offset-2 decoration-[#d8b892] hover:text-[#3f3d39] hover:decoration-[#8b6b4a] transition-colors"
      >
        {children}
      </a>
    ),

    img: ({ src, alt }) => (
      // eslint-disable-next-line @next/next/no-img-element
      <img
        src={src}
        alt={alt ?? ""}
        className="my-6 w-full rounded-xl border border-[#e2d8c8] object-cover"
      />
    ),

    table: ({ children }) => (
      <div className="my-6 w-full overflow-x-auto rounded-xl border border-[#e2d8c8]">
        <table className="w-full text-[14.5px]">
          {children}
        </table>
      </div>
    ),

    thead: ({ children }) => (
      <thead className="bg-[#efe7db] text-[#3f3d39]">{children}</thead>
    ),

    th: ({ children }) => (
      <th className="px-4 py-3 text-left font-semibold text-[13px] uppercase tracking-wide text-[#6b665e]">
        {children}
      </th>
    ),

    td: ({ children }) => (
      <td className="border-t border-[#e2d8c8] px-4 py-3 text-[#52525c]">
        {children}
      </td>
    ),

    ...components,
  }
}

// Plain object export for use with next-mdx-remote (not a React hook context).
// useMDXComponents contains no hook calls; the name only triggers the lint rule.
// eslint-disable-next-line react-hooks/rules-of-hooks
export const mdxComponents = useMDXComponents({})
